prima_app/urls.py
from django.urls import path
from prima_app.views import homepage
from prima_app.views import welcome
from prima_app.views import lista
from prima_app.views import chi_siamo
from prima_app.views import variabili
from prima_app.views import index
app_name="prima_app"
urlpatterns=[
  path('homepage', homepage, name='homepage'),
  path('welcome', welcome, name='welcome'),
  path('lista', lista, name='lista'), 
  path('chi_siamo', chi_siamo, name='chi_siamo'),
  path('variabili', variabili, name='variabili'),
  path('', index, name='index')
  

]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import index_root
urlpatterns = [
    path('admin/', admin.site.urls),
    path('prima_app/',include("prima_app.urls",namespace="prima_app")),
    path('', index_root, name='index_root')
    path('seconda_app/',include("seconda_app.urls",namespace="seconda_app"))
]

seconda_app/urls.py
from django.urls import path
from prima_app.views import homepage
from prima_app.views import welcome
from prima_app.views import lista
from prima_app.views import chi_siamo
from prima_app.views import variabili
from prima_app.views import index
app_name="seconda_app"
urlpatterns=[
  path('es_if', es_if, name='es_if')
  ]

urls.py
#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys

from django.urls import path
from prima_app.views import homepage

app_name="prima_app"
urlpatterns=[
    path('', homepage, name='homepage'),
]

seconda_app/models.py
from django.db import models

# Create your models here.

prima_app/views.py
from django.shortcuts import render

# Create your views here.

def homepage(request):
    return render(request,"prima_app/homepage.html")
def welcome(request):
    return render(request,"prima_app/welcome.html")
def lista(request):
    return render(request,"prima_app/lista.html") 
def chi_siamo(request):
    return render(request,"prima_app/chi_siamo.html") 
def variabili(request):
    context= {
        'var1': 'Prima variabile',
        'var2': 'Seconda variabile',
        'var3': 'Terza variabile'
    }
    return render(request, "variabili.html",context) 
def index(request):
     return render(request,"prima_app/index.html")

primo_progetto/views.py
from django.shortcuts import render

# Create your views here.


def index_root(request):
    return render(request,"index_root.html")

seconda_app/views.py
from django.shortcuts import render

# Create your views here.

prima_app/templates/prima_app/chi_siamo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=1.0, initial-scale=1.0">
    <title> </title>
</head>
<body>
    <h1>Chi Siamo</h1>
</body>
</html> 

prima_app/templates/prima_app/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=1.0, initial-scale=1.0">
    <title>Homepage</title>
</head>
<body>
    <h1>Benvenuto</h1>
</body>
</html> 

prima_app/templates/prima_app/index.html
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset=""UTF-8">
    <title>Index</title>
</head>
<body>
    <ol>
        <li><a href="{% url 'prima_app:homepage'&}">Home page benvenuto</a></li>
        <li><a href="{% url 'prima_app:welcome'&}">Welcome</a></li>
        <li><a href="{% url 'prima_app:lista'&}">Lista</a></li>
        <li><a href="{% url 'prima_app:chi_siamo'&}">Chi siamo</a></li>
        <li><a href="{% url 'prima_app:variabili'&}">variabili</a></li>
    </ol>
</body>
</html> 

prima_app/templates/prima_app/lista.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=1.0, initial-scale=1.0">
    <title>Lista</title>
</head>
<body>
   <ol> Primo </ol>
   <ol> Secondo </ol>
   <ol> Terzo </ol>
</body>
</html> 

prima_app/templates/prima_app/variabili.html
<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewpoint" content=""width=device-width, intial-scale="1.0">
    <title>Variabili</title>
</head>
<body>
    <ol>
        <li>{{var1}}</li>
        <li>{{var2}}</li>
        <li>{{var3}}</li>
    </ol>
</body>
</html>

prima_app/templates/prima_app/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=1.0, initial-scale=1.0">
    <title> </title>
</head>
<body>
    <h1>Welcome!</h1>
</body>
</html> 

seconda_app/templates/es_if.html
<body>
    <b>var1 = {{ var1 }}</b> <br/>
    <b>var2 = {{ var2 }}</b> <br/>
    <b>var3 = {{ var3 }}</b> <br/>

    {% if var1 < var2 %}
        <p><i>var1 è minore di var2</i></p>
    {% endif}

    {% if var1 > var2 %}
        <p><i>var1 è maggiore di var2</i></p>
    {% endif}

    {% if var1 <= var2 %}
        <p><i>var1 è minore o uguale di var2</i></p>
    {% endif}

    {% if var1 >= var2 %}
        <p><i>var1 è maggiore o uguale di var2</i></p>
    {% endif}

    {% if var1 == var2 %}
        <p><i>var1 è uguale a var2</i></p>
    {% endif}

    {% if var1 != var2 %}
        <p><i>var1 non è uguale a var2</i></p>
    {% endif}

    {% if var1 < var2 and var1 < var2 %}
        <p><i>var1 è minore di var2 e var3</i></p>
    {% endif}

    {% if var1 < var2 or var3 < var2 %}
        <p><i>var1 è minore di var2 o var3 è minore di var2</i></p>
    {% endif}

    {% if not var1 > var2 %}
        <p><i>var1 non è maggiore var2</i></p>
    {% endif}


    def es_if(request):
        context = {
            'var1' : 200,
            'var2' : 200,
            'var3' : 300
        }


</body>

seconda_app/templates/if_else_elif.html
<body>
    <b>var1 = {{ var1 }}</b> <br/>
    <b>var2 = {{ var2 }}</b> <br/>
    <b>var3 = {{ var3 }}</b> <br/>

    {% if var1 < var2 %}
        <p><i>var1 è minore di var2</i></p>
    {% elif var1 > var2 %}
        <p><i>var1 è maggiore di var2</i></p>
    {% else %}
        <p><i>var1 è uguale a var2</i></p>
    {% endif %}

    {% if var1 > var2 %}
    <p><i>var1 è maggiore di var2</i></p>
    {% elif var1 < var2 %}
        <p><i>var1 è minore di var2</i></p>
    {% else %}
        <p><i>var1 è uguale a var2</i></p>
    {% endif %}

     



    
</body>

templates/index_root.html
<!DOCTYPE html>
    <li><a href="/admin">Pannello admin</a></li>
    <li><a href="{% url 'prima_app:index'%}"> Index Prima app</a></li>
</html>